name: UI Tests

on:
  pull_request:
  push:
      branches:
          - main
          - 'release/**'

concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  setup-server-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ConcreteCMS
        run: "docker pull mlocati/docker5:develop-full"
        
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: "Setup Node"
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Cypress
        uses: cypress-io/github-action@v2
        with:
          runTests: false

      - name: General debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version
      

  block-test:
    runs-on: ubuntu-latest
    services:
      director:
        image: agoldis/sorry-cypress-director
        ports:
          - 1234:1234  
    strategy:
      matrix:
        browser: [firefox, chrome]
        concreteVersion: [develop, rc9]
      fail-fast: false
    needs: setup-server-develop
    steps:
      - name: Setup ConcreteCMS Server
        if: matrix.concreteVersion =='develop'  
        run: "docker run -d -p 8080:80 mlocati/docker5:develop-full"
        
      
      - name: Setup ConcreteCMS
        if: matrix.concreteVersion == 'rc9'
        run: "docker run -d -p 8080:80 -e 'CCM_ARCHIVE=https://github.com/concrete5/concrete5/tree/9.0rc' mlocati/docker5:develop-full"

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Setup Block Tests - ${{ matrix.browser }}"
        uses: cypress-io/github-action@v2
        with:
          build: npm ci
          runTests: false
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
      - name: "Run Block Tests - ${{ matrix.browser }}"
        run: "npm run ci:test -- -b ${{ matrix.browser }} --group 'Block - ${{ matrix.browser }} : ConcreteCMS' --ci-build-id `date +%s` --spec 'cypress/integration/blocks/*'"
        env:
          CYPRESS_API_URL: "http://localhost:1234/"
          CI: true
      - name: Save Screenshots and Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: block-test-failure-${{ matrix.browser }}-${{matrix.concreteVersion}}
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 2



  page-test:
    runs-on: ubuntu-latest
    services:
      director:
        image: agoldis/sorry-cypress-director
        ports:
          - 1234:1234  
    strategy:      
      matrix:
        browser: [firefox, chrome]
        concreteVersion: [develop, rc9]
      fail-fast: false
    needs: setup-server-develop
    steps:
      - name: Setup ConcreteCMS Server
        if: matrix.concreteVersion =='develop'
        run: "docker run -d -p 8080:80 mlocati/docker5:develop-full"
      
      - name: Setup ConcreteCMS
        if: matrix.concreteVersion == 'rc9'
        run: "docker run -d -p 8080:80 -e 'CCM_ARCHIVE=https://github.com/concrete5/concrete5/tree/9.0rc' mlocati/docker5:develop-full"


      - name: Checkout
        uses: actions/checkout@v2

      - name: "Page Tests - ${{ matrix.browser }}"
        uses: cypress-io/github-action@v2
        with:
          build: npm ci
          runTests: false
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
          #group: "Page - ${{ matrix.browser }} : ConcreteCMS"
          spec: cypress/integration/page/*
      - name: "Run Page Tests - ${{ matrix.browser }}"
        run: "npm run ci:test --  --spec 'cypress/integration/page/*' -b ${{ matrix.browser }} --group 'Page - ${{ matrix.browser }} : ConcreteCMS' --ci-build-id `date +%s`"
        env:
          CYPRESS_API_URL: "http://127.0.0.1:1234/"
          CI: true
      - name: Save Screenshots and Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: page-test-failure-${{ matrix.browser }}-${{matrix.concreteVersion}}
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 2
        
  dashboard-test:
    runs-on: ubuntu-latest
    services:
      director:
        image: agoldis/sorry-cypress-director
        ports:
          - 1234:1234  
    strategy:      
      matrix:
        browser: [firefox, chrome]
        concreteVersion: [develop, rc9]
      fail-fast: false
    needs: setup-server-develop
    steps:
      - name: Setup ConcreteCMS Server
        if: matrix.concreteVersion == 'develop'
        run: "docker run -d -p 8080:80 mlocati/docker5:develop-full"
        
      
      - name: Setup ConcreteCMS
        if: matrix.concreteVersion == 'rc9'
        run: "docker run -d -p 8080:80 -e 'CCM_ARCHIVE=https://github.com/concrete5/concrete5/tree/9.0rc' mlocati/docker5:develop-full"

      - name: Checkout
        uses: actions/checkout@v2

      - name: "Dashboard Tests - ${{ matrix.browser }}"
        uses: cypress-io/github-action@v2
        with:
          build: npm install
          runTests: false
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120

      - name: "Run Dashboard Tests - ${{ matrix.browser }}"
        run: "npm run ci:test --  --spec 'cypress/integration/dashboard/*' -b ${{ matrix.browser }} --group 'Dashboard - ${{ matrix.browser }} : ConcreteCMS' --ci-build-id `date +%s`"
        env:
          CYPRESS_API_URL: "http://127.0.0.1:1234/"
          CI: true

      - name: Save Screenshots and Videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: dashboard-test-failure-${{ matrix.browser }}-${{matrix.concreteVersion}}
          path: |
            cypress/screenshots
            cypress/videos
          retention-days: 2
